name: dreamcast
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,`
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any
  get: any
  shared_preferences: any
  flutter_svg: any
  auto_size_text: any
  cached_network_image: any
  flutter_inappwebview: any
  smooth_page_indicator: any
  get_storage: any # used for local storage
  image_picker: any # pick image from camera/gallery
  flutter_rating_bar: any
  intl: any
  url_launcher: any
  mime: any
  http: any
  page_view_indicators: any
  lottie: any
  permission_handler: any
  firebase_core: any
  firebase_database: any
  firebase_auth: any
  firebase_analytics: any
  firebase_crashlytics: any
  firebase_messaging: any
  timezone: any
  flutter_local_notifications: any
  csv: any
  open_file: any
  add_2_calendar: any
  country_code_picker: any
  internet_connection_checker: ^1.0.0+1
  flutter_downloader: any
  external_path: any
  package_info_plus: any
  pinput: any
  image_size_getter: any
  carousel_slider: any
  percent_indicator: any
  share_plus: any
  flutter_widget_from_html: any
  camera: any
  qr_flutter: any
  audioplayers: any
  file_picker: any
  video_thumbnail: any
  scroll_snap_list: any
  amazon_cognito_identity_dart_2: any
  connectivity_plus: any
  awesome_notifications: any
  skeletonizer: any
  image_cropper: any
  dio: any
  syncfusion_flutter_pdfviewer: any
  flutter_snake_navigationbar: any
  gradient_borders: any
  signin_with_linkedin: ^1.0.1
  scrollable_positioned_list: any
  dropdown_button2: any
  sign_in_with_apple: any
  simple_gradient_text: any
  flutter_linkify: any
  flutter_contacts: any
  readmore: any
  saver_gallery: ^4.0.1
  flutter_keyboard_visibility: any
  video_player: any
  webview_flutter: any
  device_info_plus: any
  app_links: any
  fluttertoast: any
  mobile_scanner: any
  torch_light: any
  toastification: any
  focused_menu: any
  flutter_secure_storage: any
  visibility_detector: any
  image_gallery_saver_plus: any
  auto_size_text_field: any
  flutter_colorpicker: any
  flutter_image_compress: any
  image_picker_android: any
  workmanager: any
  widget_zoom: any
  syncfusion_flutter_calendar:
  jailbreak_root_detection: any
  otp_pin_field: any

#dependency_overrides:
#  webview_flutter_android: 3.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/file/
    - assets/svg/
    - assets/animated/
    - assets/sounds/

  fonts:
    - family: FigTree
      fonts:
        - asset: assets/fonts/figtree/FigTree-Bold.otf
        - asset: assets/fonts/figtree/FigTree-SemiBold.otf
        - asset: assets/fonts/figtree/FigTree-Medium.otf
        - asset: assets/fonts/figtree/FigTree-Regular.otf

    - family: Fester
      fonts:
        - asset: assets/fonts/fester/Fester-Bold.otf
        - asset: assets/fonts/fester/Fester-SemiBold.otf
        - asset: assets/fonts/fester/Fester-Regular.otf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

